### ISSUE TITLE
"Disable Server Filter" option not saving

### ISSUE THREAD

**Issue by Chris230291** [fairbird/NCam#23]
On a Newcamd reader the option ` Disable Server Filter` does not save.
It is enabled by default and it doesnt seem possible to disable it.

**Comment by fairbird** [comment]
From (ncam.server) you need to set in Newcamd reader
> enable                        = 0
or from web site browser (READERS) opttion press on any reader you want to disable it (With me no problem)

![Selection_001](https://github.com/fairbird/NCam/assets/1761779/51a0d4de-c91a-498e-81fe-f5d03b728b84)
![Selection_002](https://github.com/fairbird/NCam/assets/1761779/e19abb08-403e-4c06-8ca1-24f88fa60f63)

**Comment by Chris230291** [comment]
This is not the same option. Sorry for not being clearer.

![image](https://github.com/fairbird/NCam/assets/5328818/5630c5bd-2e32-4cb0-92d0-df96ee7901b9)

**Comment by fairbird** [comment]
Are you sure using my ncam version ?!!!

![Selection_001](https://github.com/fairbird/NCam/assets/1761779/3558662e-9a80-4628-82c6-85aa1b8f4c66)

**Comment by Chris230291** [comment]
Yes. I compile it here https://github.com/Chris230291/NCam-Docker

Untick setting, save, restart ncam and it is checked again.

EDIT: Maybe issue with oscam too? https://trac.streamboard.tv/oscam/ticket/3621#no1

**Comment by fairbird** [comment]
ok .. Clear
That was not issue .. It is normally ..
NCam automatically adds it if the server requires it.
The tick comes back again because of the remote server, which is automatically switched back on by both ncam and oscam.

![2023-08-10 19-44-36](https://github.com/fairbird/NCam/assets/1761779/b16bb674-b806-4ec5-a2c7-bce261a1f521)

Since Mgclient is enabled on the remote server...
If the remote server is configured differently, it won't switch back.

if you want to test it ?! Then pull out the internet connection from your device, set the (disable server filter) to 0 and restart ncam again, the tick will not come back, but if you plug the internet back in and connect to the remote server, and there the mgclien is on then, [this](https://github.com/fairbird/NCam/blob/master/module-newcamd.c#L1874) turns it back on...

I hope it is clear for you !!

**Comment by Chris230291** [comment]
Thank you.
