### ISSUE TITLE
Add links to wiki

### ISSUE THREAD

**Issue by MegaV0lt** [fairbird/NCam#24]
All links in webif that should point to the wiki are not working. Please readd or make own wiki

**Comment by fairbird** [comment]
The public NCam on GitHub doesn't have the help feature because all the information is in the
https://github.com/fairbird/NCam/tree/master/Distribution/doc

Also I don't know exactly how the wiki works on GitHub either. I did not try it before !!
But I think. I could use this too later !!
And my English language skills not excellent in writing and grammar. So I need some help from other !!
